### PR TITLE
Updating Nexus integration

### PR DESCRIPTION
**Pull request by jobara**
Updated the nexus branch to work with the latest version of the WOAS sim.

### CODE REVIEW

**Comment by jobara** [comment]
@jessegreenberg when you have a chance, could you please look over this PR.

**Comment by jessegreenberg** [comment]
@jobara merge complete, I tested the changes in the branch, all seems to be well except for this error:
```
WebSocket connection to 'ws://localhost:9081/bindModel/nexus.sensors/orientation' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Which would presumably go away when the sim is hooked up to the nexus.

Please let me know if there is anything else!

**Comment by jobara** [comment]
@jessegreenberg yes, that's correct. I added some information in the code comment which should help with getting the Nexus running in a state that will work with WAOS, and should help with testing this PR or playing with later.

**Comment by jobara** [comment]
@jessegreenberg thanks for merging :)

**Pull request merged**
